# IngresRoute http
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: whoami-notls
  namespace: default

spec:
  entryPoints: 
    - web
  routes:
  - match: Host(`{YOUR-DNS-NAME}`) 
    kind: Rule
    services:
    - name: whoami
      port: 80
    # redirect http to https
    #middlewares: 
    #- name: secured



# IngresRoute https
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: whoami-tls
  namespace: default
spec:
  entryPoints: 
    - websecure
  routes:
  - match: Host(`{YOUR-DNS-NAME}`) 
    kind: Rule
    services:
    - name: whoami
      port: 80
    middlewares: 
    - name: https-redirect
  tls:
    certResolver: default

