version: '3'

services:
  app:
     image: traefik:v1.6.5
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - $PWD/management/traefik/traefik.toml:/etc/traefik/traefik.toml
       - $PWD/management/traefik/acme:/etc/traefik/acme
     ports:
       - 80:80
       - 443:443
       - 8100:8080
     deploy:
       placement:
         constraints:
           - node.role == manager
     
networks:
   default:
    external:
      name:  imixs-proxy-net